#test exception 8

int main() {
  var x : int;
  x = 0;
  x = x || (1 / x);
  return x;
}