#test exception 8

int main() {
  return 1 / (2 - (1 << 33));
}
